spring:
  application:
    name: sboot-ibge-ipca-insights-api
  main:
    banner-mode: "off"
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: ibge_ipca_history_db
      username: admin
      password: admin
      authentication-database: admin
      uuid-representation: standard
      auto-index-creation: true

ibge:
  sidra:
    ipca:
      table1737:
        api: "https://apisidra.ibge.gov.br/values/t/1737/n1/all/v/all/p/all/d/v63 2,v69 2,v2266 13,v2263 2,v2264 2,v2265 2"
