spring:
  application:
    name: sboot-ibge-ipca-insights-api

ibge:
  sidra:
    ipca:
      table1737:
        api: "https://apisidra.ibge.gov.br/values/t/1737/n1/all/v/all/p/all/d/v63 2,v69 2,v2266 13,v2263 2,v2264 2,v2265 2"
